# A plugin by MatiasME

chest-name: "&5&l[&3&lGUIPotsShop&5&l]"

potions:
  night: true
  night-ext: true
  night-splash: true
  night-splash-ext: true

  invi: true
  invi-ext: true
  invi-splash: true
  invi-splash-ext: true

  jump: true
  jump-ext: true
  jump-up: true
  jump-splash: true
  jump-splash-ext: true
  jump-splash-up: true

  fire: true
  fire-ext: true
  fire-splash: true
  fire-splash-ext: true

  speed: true
  speed-ext: true
  speed-up: true
  speed-splash: true
  speed-splash-ext: true
  speed-splash-up: true

  heal: true
  heal-up: true
  heal-splash: true
  heal-splash-up: true

  poison: true
  poison-ext: true
  poison-up: true
  poison-splash: true
  poison-splash-ext: true
  poison-splash-up: true

  regen: true
  regen-ext: true
  regen-up: true
  regen-splash: true
  regen-splash-ext: true
  regen-splash-up: true

  strength: true
  strength-up: true
  strength-ext: true
  strength-splash: true
  strength-splash-ext: true
  strength-splash-up: true

potions-cost:
  night: 100
  night-ext: 100
  night-splash: 100
  night-splash-ext: 100

  invi: 100
  invi-ext: 100
  invi-splash: 100
  invi-splash-ext: 100

  jump: 100
  jump-ext: 100
  jump-up: 100
  jump-splash: 100
  jump-splash-ext: 100
  jump-splash-up: 100

  fire: 100
  fire-ext: 100
  fire-splash: 100
  fire-splash-ext: 100

  speed: 100
  speed-ext: 100
  speed-up: 100
  speed-splash: 100
  speed-splash-ext: 100
  speed-splash-up: 100

  heal: 100
  heal-up: 100
  heal-splash: 100
  heal-splash-up: 100

  poison: 100
  poison-ext: 100
  poison-up: 100
  poison-splash: 100
  poison-splash-ext: 100
  poison-splash-up: 100

  regen: 100
  regen-ext: 100
  regen-up: 100
  regen-splash: 100
  regen-splash-ext: 100
  regen-splash-up: 100

  strength: 100
  strength-up: 100
  strength-ext: 100
  strength-splash: 100
  strength-splash-ext: 100
  strength-splash-up: 100

messages:
  not-permission: "&4You don't have permission for this command."
  bought-potion: "&3You have bought a potion."
  cant-buy: "&3You do not have enough money."
  economy-error: "&4An error has occurred in the economy: "
  pots-price-lore: "&3This potion is worth: &2"
  full-inventory: "&3The inventory is full"