# A plugin by MatiasME

chest-name: "[GUIPotsShop]"

potions-type-cost: money # or level

potions:
  night: true
  night-ext: true
  night-splash: false
  night-splash-ext: false

  invi: false
  invi-ext: false
  invi-splash: false
  invi-splash-ext: false

potions-cost:
  night: 100
  night-ext: 100
  night-splash: 100
  night-splash-ext: 100

  invi: 100
  invi-ext: 100
  invi-splash: 100
  invi-splash-ext: 100


messages:
  not-permission: "&2You don't have permission for this command."